# Generated by Django 3.1.6 on 2021-02-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('chi_name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='chi_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
