# Generated by Django 3.1.6 on 2021-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0003_auto_20210203_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='category',
            name='chi_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.ManyToManyField(to='doctorapi.Category'),
        ),
    ]
