# Generated by Django 3.1.6 on 2021-02-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0005_auto_20210203_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=60, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctorapi.district')),
            ],
        ),
    ]
