# Generated by Django 3.1.6 on 2021-02-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0006_district_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doctorapi.district'),
        ),
    ]
