# Generated by Django 3.1.6 on 2021-02-04 07:30

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('doctorapi', 'district')
    for row in MyModel.objects.all():
        row.string_id = uuid.uuid4()
        row.save(update_fields=['string_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('doctorapi', '0011_district_string_id'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
